export const portfolios = [
  {
    name: "Homeprime",
    url: "https://homeprime.it",
    logo: "https://homeprime.it/wp-content/themes/yootheme/cache/70/HomePrime-logo-70d2c8cb.png",
    category: "Web App",
  },
  {
    name: "Karmika Comunicazione",
    url: "https://karmika.net",
    logo: "https://karmika.net/wp-content/uploads/2022/01/logo-karmika-logo-hq-reg-ok.png",
    category: "Sito Vetrina",
  },
  {
    name: "OuiFleurs",
    url: "https://www.ouifleurs.com",
    logo: "https://www.ouifleurs.com/wp-content/uploads/2024/02/logo-rosso-solo-scritta-menu.svg",
    category: "Ecommerce",
  },
  {
    name: "Larissa Barton",
    url: "https://larissabarton.com",
    logo: "https://larissabarton.com/wp-content/uploads/2024/04/logo-copertina-bk.png",
    category: "Sito Vetrina",
  },
  {
    name: "GekoForGreen",
    url: "https://gekoforgreen.com/",
    logo: "https://gekoforgreen.com/wp-content/uploads/2021/05/logo-GEKO-GREEN.png",
    category: "Portale",
  },
  {
    name: "Franca Soavi",
    url: "https://francasoavi.com/",
    logo: "https://francasoavi.com/wp-content/uploads/2023/05/logo-Franca-ok.png",
    category: "Sito Vetrina",
  },
  {
    name: "Fable Farm",
    url: "https://fablefarm.it/",
    logo: "https://fablefarm.it/wp-content/uploads/2022/11/fable-farm-logo-hi-q.png",
    category: "Sito Vetrina",
  },
  {
    name: "Albero della Vita",
    url: "https://alberodellavitaparma.it/",
    logo: "https://alberodellavitaparma.it/wp-content/uploads/2023/06/Logo-Albero-della-Vita-38847a5e-240w.png",
    category: "Ecommerce",
  },
  {
    name: "Scuola626",
    url: "https://scuola626.com/",
    logo: "https://scuola626.com/wp-content/uploads/2023/02/logo-2017-ok-ok-ok.png",
    category: "Portale",
  },
  {
    name: "Pyou ES",
    url: "https://pyou.es/",
    logo: "https://pyou.es/wp-content/uploads/2022/09/pyou-es-logo-ok.png",
    category: "Portale",
  },
  {
    name: "Pyou UK",
    url: "https://pyou.uk/",
    logo: "https://pyou.es/wp-content/uploads/2022/09/pyou-es-logo-ok.png",
    category: "Portale",
  },
  {
    name: "Pyou HK",
    url: "https://pyou.com.hk/",
    logo: "https://pyou.es/wp-content/uploads/2022/09/pyou-es-logo-ok.png",
    category: "Portale",
  },
  {
    name: "Caccianemici",
    url: "https://www.caccianemici.it/",
    logo: "https://www.caccianemici.it/wp-content/uploads/2020/09/logo-home.png",
    category: "Ecommerce",
  },
  {
    name: "Maen Tech",
    url: "https://www.maen.tech/",
    logo: "https://www.maen.tech/wp-content/uploads/2021/04/logo-margotta-energia.png",
    category: "Ecommerce",
  },
  {
    name: "Cento Sports",
    url: "https://centosports.it/",
    logo: "https://centosports.it/wp-content/uploads/2022/04/Centosport-logo-vettoriale.png",
    category: "Ecommerce",
  },
  {
    name: "Frè",
    url: "https://frefrefre.com/",
    logo: "https://frefrefre.com/wp-content/uploads/2023/09/FRE-BLACK-anime.svg",
    category: "Sito Vetrina",
  },
  {
    name: "Dynsphotos",
    url: "https://www.dynsphotos.it/",
    logo: "https://www.dynsphotos.it/wp-content/uploads/2023/06/Logo-biancosfondo.png",
    category: "Sito Vetrina",
  },
  {
    name: "Temporama Alchemico",
    url: "https://temporamaalchemico.com/",
    logo: "https://temporamaalchemico.com/wp-content/uploads/2022/12/TEMPORAMA-LOGO-dark.png",
    category: "Sito Vetrina",
  },
];
